name: base
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=3.7.7
    - python=3.5.3
    - r-dplyr
    - r-ggplot2
    - r-reshape2
    - r-tidyverse
    - pip
    - pip:
        - pandas
        - matplotlib
        - numpy
        - scipy
        - scikitlearn
